cities <- data.frame()

cities <- rbind(cities,  data.frame(x = 0.15,	y = 5.35, 	label="Aachen", 		 id = "Aachen" 	))
cities <- rbind(cities,  data.frame(x = 4.55,	y = 1.6 , 	label="Augsburg", 		 id = "Augsburg" ))
cities <- rbind(cities,  data.frame(x = 5.2,	y = 4 , 	label="Bayreuth", 		 id = "Bayreuth" ))
cities <- rbind(cities,  data.frame(x = 6.8,	y = 7.8 , 	label="Berlin", 		 id = "Berlin" 	))
cities <- rbind(cities,  data.frame(x = 2.4,	y = 7.1 , 	label="Bielefeld", 		 id = "Bielefeld" ))
cities <- rbind(cities,  data.frame(x = 1.05,	y = 5.25, 	label="Bonn", 			 id = "Bonn" 		))
cities <- rbind(cities,  data.frame(x = 4.3,	y = 7.35, 	label="Braunschweig", 	 id = "Braunschweig"))
cities <- rbind(cities,  data.frame(x = 2.8,	y = 8.7 , 	label="Bremen", 		 id = "Bremen" 	))
cities <- rbind(cities,  data.frame(x = 2.6,	y = 9.4 , 	label="Bremerhaven",	 id = "Bremerhaven"))
cities <- rbind(cities,  data.frame(x = 6.45,	y = 5.33, 	label="Chemnitz", 		 id = "Chemnitz" ))
cities <- rbind(cities,  data.frame(x = 7.65,	y = 6.7 , 	label="Cottbus", 		 id = "Cottbus" 	))
cities <- rbind(cities,  data.frame(x = 2.45,	y = 3.9 , 	label="Darmstadt", 		 id = "Darmstadt" ))
cities <- rbind(cities,  data.frame(x = 1.45,	y = 6.35, 	label="Dortmund", 		 id = "Dortmund" ))
cities <- rbind(cities,  data.frame(x = 7.2,	y = 5.65, 	label="Dresden", 		 id = "Dresden" 	))
cities <- rbind(cities,  data.frame(x = 0.8,	y = 6.3 , 	label="Duisburg", 		 id = "Duisburg" ))
cities <- rbind(cities,  data.frame(x = 0.85,	y = 5.95, 	label="Dusseldorf", 	 id = "Dusseldorf"))
cities <- rbind(cities,  data.frame(x = 4.7,	y = 5.45, 	label="Erfurt", 		 id = "Erfurt" 	))
cities <- rbind(cities,  data.frame(x = 1,		y = 6.3 , 	label="Essen", 			 id = "Essen" 		))
cities <- rbind(cities,  data.frame(x = 3.4,	y = 11.1, 	label="Flensburg", 		 id = "Flensburg" ))
cities <- rbind(cities,  data.frame(x = 2.5,	y = 4.2 , 	label="Frankfurt", 		 id = "Frankfurt" ))
cities <- rbind(cities,  data.frame(x = 1.62,	y = 1.12, 	label="Freiburg", 		 id = "Freiburg" ))
cities <- rbind(cities,  data.frame(x = 5.7,	y = 5.33, 	label="Gera", 			 id = "Gera" 		))
cities <- rbind(cities,  data.frame(x = 3.7,	y = 6.3 , 	label="Gottingen", 		 id = "Gottingen" ))
cities <- rbind(cities,  data.frame(x = 5.6,	y = 6.25, 	label="Halle", 			 id = "Halle" 		))
cities <- rbind(cities,  data.frame(x = 3.8,	y = 9.3 , 	label="Hamburg", 		 id = "Hamburg" 	))
cities <- rbind(cities,  data.frame(x = 3.5,	y = 7.55, 	label="Hannover", 		 id = "Hannover" ))
cities <- rbind(cities,  data.frame(x = 2.5,	y = 3.2 , 	label="Heidelberg", 	 id = "Heidelberg"))
cities <- rbind(cities,  data.frame(x = 3,		y = 2.8 , 	label="Heilbronn", 		 id = "Heilbronn" ))
cities <- rbind(cities,  data.frame(x = 5.1,	y = 2.2 , 	label="Ingolstadt", 	 id = "Ingolstadt"))
cities <- rbind(cities,  data.frame(x = 1.6,	y = 3.25, 	label="Kaiserslautern",  id = "Kaiserslautern"))
cities <- rbind(cities,  data.frame(x = 2.15,	y = 2.65, 	label="Karlsruhe", 		 id = "Karlsruhe" ))
cities <- rbind(cities,  data.frame(x = 3.25,	y = 5.95, 	label="Kassel", 		 id = "Kassel" 	))
cities <- rbind(cities,  data.frame(x = 4,		y = 10.4, 	label="Kiel", 			 id = "Kiel" 		))
cities <- rbind(cities,  data.frame(x = 0.95,	y = 5.6 , 	label="Koln", 			 id = "Koln" 		))
cities <- rbind(cities,  data.frame(x = 6,		y = 6.05 , 	label="Leipzig", 		 id = "Leipzig" 	))
cities <- rbind(cities,  data.frame(x = 4.45,	y = 9.75, 	label="Lubeck", 		 id = "Lubeck" 	))
cities <- rbind(cities,  data.frame(x = 4.15,	y = 8.8 , 	label="Luneburg", 		 id = "Luneburg" ))
cities <- rbind(cities,  data.frame(x = 5.25,	y = 7.15, 	label="Magdeburg", 		 id = "Magdeburg" ))
cities <- rbind(cities,  data.frame(x = 2.1,	y = 4 , 	label="Mainz", 			 id = "Mainz" 		))
cities <- rbind(cities,  data.frame(x = 2.3,	y = 3.35, 	label="Mannheim", 		 id = "Mannheim" ))
cities <- rbind(cities,  data.frame(x = 0.5,	y = 5.95, 	label="Monchengladbach", id = "Monchengladbach"))
cities <- rbind(cities,  data.frame(x = 5.25,	y = 1.35, 	label="Munchen", 		 id = "Munchen" 	))
cities <- rbind(cities,  data.frame(x = 1.6,	y = 7.05, 	label="Munster", 		 id = "Munster" 	))
cities <- rbind(cities,  data.frame(x = 4.8,	y = 3.25, 	label="Nurnberg", 		 id = "Nurnberg" ))
cities <- rbind(cities,  data.frame(x = 2.3,	y = 8.75, 	label="Oldenburg", 		 id = "Oldenburg" ))
cities <- rbind(cities,  data.frame(x = 2,		y = 7.45, 	label="Osnabruck", 		 id = "Osnabruck" ))
cities <- rbind(cities,  data.frame(x = 2.6,	y = 6.6 , 	label="Paderborn", 		 id = "Paderborn" ))
cities <- rbind(cities,  data.frame(x = 2.43,	y = 2.4 , 	label="Pforzheim", 		 id = "Pforzheim" ))
cities <- rbind(cities,  data.frame(x = 5.75,	y = 2.65, 	label="Regensburg", 	 id = "Regensburg"))
cities <- rbind(cities,  data.frame(x = 5.65,	y = 10.1, 	label="Rostock", 		 id = "Rostock" 	))
cities <- rbind(cities,  data.frame(x = 0.85,	y = 3 , 	label="Saarbrucken", 	 id = "Saarbrucken"))
cities <- rbind(cities,  data.frame(x = 3,		y = 2.25, 	label="Stuttgart", 		 id = "Stuttgart" ))
cities <- rbind(cities,  data.frame(x = 0.55,	y = 3.8 , 	label="Trier", 			 id = "Trier" 		))
cities <- rbind(cities,  data.frame(x = 3.65,	y = 1.7 , 	label="Ulm", 			 id = "Ulm" 			))
cities <- rbind(cities,  data.frame(x = 2.1,	y = 4.2 , 	label="Wiesbaden", 		 id = "Wiesbaden" ))
cities <- rbind(cities,  data.frame(x = 4.55,	y = 7.6 , 	label="Wolfsburg", 		 id = "Wolfsburg" ))
cities <- rbind(cities,  data.frame(x = 3.7,	y = 3.75, 	label="Wurzburg", 		 id = "Wurzburg" ))